backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
editor:
  preview: false

media_folder: "/assets/img/"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - name: "case-studies"
    label: "Case Studies"
    create: true
    slug: "{{slug}}"
    folder: "category/case-studies"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title Link - for reviews and exhibits", name: "title_link", widget: "string", required: false }
      - { label: "Item Image", name: "item_image", widget: "image", choose_url: true, default: "/assets/img/byzantine1.png", media_library: { config: { multiple: false } } }
      - { label: "Item Image Caption", name: "item_image_caption", widget: "markdown", required: false }
      - label: "Slider Images"
        name: "slider_images"
        widget: "list"
        fields:
          - { label: "Slider Image", name: "slider_image", widget: "image", choose_url: true, default: "/assets/img/byzantine1.png", media_library: { config: { multiple: false } } }
          - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Start Year", name: "start_year", widget: "number", default: 1150, max: 1750, min: 1150, required: false }
      - { label: "End Year", name: "end_year", widget: "number", default: 1750, max: 1750, min: 1150, required: false }
      - { label: "Text", name: "text", widget: "markdown", required: false }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Type (Medium)", name: "type", widget: "list", required: false }
      - { label: "Locations", name: "locations", widget: "list", required: false }
      - { label: "Subjects", name: "subjects", widget: "list", required: false }
      - { label: "Map Point", name: "map_point", widget: "map", required: false }
      - { label: "Make Public", name: "make_public", widget: "boolean", default: false }

