backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "/assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "items"
    label: "Items"
    create: true
    slug: "{{slug}}"
    folder: "items"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Affiliation", name: "affiliation", widget: "string" }
      - { label: "Latitude", name: "latitude", widget: "number" }
      - { label: "Longitude", name: "longitude", widget: "number" }
      - { label: "Category", name: "category", widget: "select", options: [
          { label: "Ongoing Projects", value: "ongoing-projects" },
          { label: "Completed Projects", value: "completed-projects" },
          { label: "Exhibitions", value: "exhibitions" },
          { label: "Publications", value: "publications" },
          { label: "Conferences", value: "conferences" },
          { label: "Workshops", value: "workshops" },
          { label: "Lectures", value: "lectures" },
          { label: "Other", value: "other" }
        ] }
      - { label: "Make Public", name: "make_public", widget: "boolean", default: true }
      - { label: "Item Image Caption", name: "item_image_caption", widget: "markdown", required: false }
      
      - { label: "Subject", name: "subject_m2m", widget: "relation", collection: 'subject', search_fields: ['title'], value_field: 'id', display_fields: ['title'] }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Location (Multiple)", name: "location_m2m", widget: "relation", collection: 'location', search_fields: ['title'], value_field: 'id', display_fields: ['title'] }
      - { label: "Medium (Multiple)", name: "medium_m2m", widget: "relation", collection: 'medium', search_fields: ['title'], value_field: 'id', display_fields: ['title'] }
      - { label: "Start Year", name: "start_year", widget: "number" }
      - { label: "End Year", name: "end_year", widget: "number" }
      - { label: "Content", name: "content", widget: "markdown" }


